require 'virtual/method_defined'
require 'virtual/virtual_method'
require 'virtual/pure_method'
require 'virtual/protocol_method'
require 'virtual/macro'
require 'virtual/activate'
require 'virtual/virtual'
